k8s_version: "1.30"
pod_network_cidr: "10.244.0.0/16"
nfs_export_path: "/srv/nfs/kubedata"
nfs_export_options: "*(rw,sync,no_subtree_check,no_root_squash)"
nfs_storage_class_name: "nfs-client"
datavolume_wait_timeout: "20m"
kubevirt_wait_timeout: "10m"
