#cloud-config
users:
  - name: ${cloudinit_user}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys:
      - ${ssh_public_key}
disable_root: true
preserve_hostname: false
